### PR TITLE
Some code cleanup for the example

### PR DESCRIPTION
**Pull request by vicb**
Include PR #73

### CODE REVIEW

**Comment by vicb** [comment]
@cbracken I've addressed your feedback

**Comment by cbracken** [comment]
Thanks for the quick turnaround!

**Comment by vicb** [comment]
@cbracken you're welcome.

Have you seen my previous question: "Have you used GH to add your comments ?"

**Comment by cbracken** [comment]
Yep; I added my comments via the usual github web interface, if that's what you mean.

**Comment by vicb** [comment]
that was the sense of my question. thanks.

**Pull request merged**
