### PR TITLE
Fix documentation syntax error

### PR DESCRIPTION
**Pull request by danschultz**
I'm using Dart Editor version 0.5.20_r24160. `build.dart` is throwing an error because of a syntax typo with the documentation.

```
Uncaught Error: RangeError: value 381 not in range 0..380
Stack Trace:
#0      _StringBase.indexOf (dart:core-patch/string_patch.dart:109:7)
#1      Parser.parseCommentReferences (package:analyzer_experimental/src/generated/parser.dart:1756:38)
#2      Parser.parseDocumentationComment (package:analyzer_experimental/src/generated/parser.dart:2164:63)
#3      Parser.parseCommentAndMetadata (package:analyzer_experimental/src/generated/parser.dart:1653:48)
#4      Parser.parseClassMember (package:analyzer_experimental/src/generated/parser.dart:1439:68)
#5      Parser.parseClassMembers (package:analyzer_experimental/src/generated/parser.dart:1555:46)
#6      Parser.parseClassDeclaration (package:analyzer_experimental/src/generated/parser.dart:1417:34)
#7      Parser.parseCompilationUnitMember (package:analyzer_experimental/src/generated/parser.dart:1877:35)
#8      Parser.parseCompilationUnit2 (package:analyzer_experimental/src/generated/parser.dart:1839:66)
#9      Parser.parseCompilationUnit (package:analyzer_experimental/src/generated/parser.dart:330:35)
#10     Parser.parseCompilationUnit (package:analyzer_experimental/src/generated/parser.dart:331:7)
#11     parseCompilationUnit (package:web_ui/src/dart_parser.dart:135:41)
#12     parseDartCode (package:web_ui/src/dart_parser.dart:97:34)
#13     Compiler._processDartFile (package:web_ui/src/compiler.dart:303:22)
#14     Compiler._parseDartFile._parseDartFile.<anonymous closure> (package:web_ui/src/compiler.dart:259:27)
#15     _ThenFuture._zonedSendValue (dart:async/future_impl.dart:355:24)
#16     _TransformFuture._sendValue.<anonymous closure> (dart:async/future_impl.dart:332:48)
#17     _ZoneBase._runInZone (dart:async/zone.dart:70:17)
#18     _ZoneBase._runUnguarded (dart:async/zone.dart:98:22)
#19     _ZoneBase.executeCallback (dart:async/zone.dart:56:23)
#20     _TransformFuture._sendValue (dart:async/future_impl.dart:332:26)
#21     _FutureImpl._setValue (dart:async/future_impl.dart:185:26)
#22     _CatchErrorFuture._zonedSendValue (dart:async/future_impl.dart:373:14)
#23     _TransformFuture._sendValue.<anonymous closure> (dart:async/future_impl.dart:332:48)
#24     _ZoneBase._runInZone (dart:async/zone.dart:70:17)
#25     _ZoneBase._runUnguarded (dart:async/zone.dart:98:22)
#26     _ZoneBase.executeCallback (dart:async/zone.dart:56:23)
#27     _TransformFuture._sendValue (dart:async/future_impl.dart:332:26)
#28     _FutureImpl._setValue (dart:async/future_impl.dart:185:26)
#29     _FutureImpl._setOrChainValue (dart:async/future_impl.dart:320:16)
#30     _ThenFuture._zonedSendValue (dart:async/future_impl.dart:361:21)
#31     _TransformFuture._sendValue.<anonymous closure> (dart:async/future_impl.dart:332:48)
#32     _ZoneBase._runInZone (dart:async/zone.dart:70:17)
#33     _ZoneBase._runUnguarded (dart:async/zone.dart:98:22)
#34     _ZoneBase.executeCallback (dart:async/zone.dart:56:23)
#35     _TransformFuture._sendValue (dart:async/future_impl.dart:332:26)
#36     _FutureImpl._setValue (dart:async/future_impl.dart:185:26)
#37     _FutureImpl._setOrChainValue (dart:async/future_impl.dart:320:16)
#38     _ThenFuture._zonedSendValue (dart:async/future_impl.dart:361:21)
#39     _TransformFuture._sendValue.<anonymous closure> (dart:async/future_impl.dart:332:48)
#40     _ZoneBase._runInZone (dart:async/zone.dart:70:17)
#41     _ZoneBase._runUnguarded (dart:async/zone.dart:98:22)
#42     _ZoneBase.executeCallback (dart:async/zone.dart:56:23)
#43     _TransformFuture._sendValue (dart:async/future_impl.dart:332:26)
#44     _FutureImpl._setValue (dart:async/future_impl.dart:185:26)
#45     _FutureImpl._setOrChainValue (dart:async/future_impl.dart:320:16)
#46     _ThenFuture._zonedSendValue (dart:async/future_impl.dart:361:21)
#47     _TransformFuture._sendValue.<anonymous closure> (dart:async/future_impl.dart:332:48)
#48     _ZoneBase._runInZone (dart:async/zone.dart:78:19)
#49     _ZoneBase._runUnguarded (dart:async/zone.dart:98:22)
#50     _ZoneBase.executeCallback (dart:async/zone.dart:56:23)
#51     _TransformFuture._sendValue (dart:async/future_impl.dart:332:26)
#52     _FutureImpl._setValue (dart:async/future_impl.dart:185:26)
#53     _SyncCompleter._setFutureValue (dart:async/future_impl.dart:54:21)
#54     _Completer.complete (dart:async/future_impl.dart:17:20)
#55     _SendPortImpl.call.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:106:27)
#56     _ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)


Unhandled exception:
RangeError: value 381 not in range 0..380
#0      _DefaultZone.handleUncaughtError.<anonymous closure> (dart:async/zone.dart:148:7)
#1      _asyncRunCallback._asyncRunCallback (dart:async/event_loop.dart:9:15)
#2      _asyncRunCallback._asyncRunCallback (dart:async/event_loop.dart:13:7)
#3      _createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:8:13)
#4      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:91:28)
#5      _Timer._createTimerHandler._handleTimeout (timer_impl.dart:99:7)
#6      _Timer._createTimerHandler.<anonymous closure> (timer_impl.dart:107:23)
#7      _ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:81:92)

```

### CODE REVIEW

**Comment by jmesserly** [comment]
looks good to me, thanks!

**Comment by BerndWessels** [comment]
The latest Editor still doesn't have this fix.

Dart Editor version 0.5.20_r24275
Dart SDK version 0.5.20.4_r24275

What do I have to do to get it?

**Comment by jmesserly** [comment]
yeah, i don't think we've uploaded to http://pub.dartlang.org/packages/route
let me see if I can

**Comment by jmesserly** [comment]
i just uploaded 0.4.5+1, let me know if it helps

**Comment by BerndWessels** [comment]
Thank you, yes it helps.

**Pull request merged**
