### PR TITLE
A lot of refactoring, some fixes

### PR DESCRIPTION
**Pull request by vicb**
I've kept separated commits so that the review is easier.

I've changed the code to make it easier to follow, it might be a matter of personal prefs though. If this is the case please pin-point the commit and the modif so that I can revert.

Tests are passing as well as before: there is one remaining issue with the last test in `test_client.html`.

### CODE REVIEW

**Comment by pavelgj** [comment]
FYI: master branch is quite old. If you're looking to contribute, see either:

https://github.com/dart-lang/route/tree/0.5.0

or

https://github.com/angular/route.dart

**Comment by vicb** [comment]
thanks @pavelgj could you please explain me the differences between dart-lang 0.5 and angular router please ?

Maybe something should be added to the README.md ? Github also allows setting the default target branch for PR...

**Comment by pavelgj** [comment]
Once there was `master` branch in `dart-lang/route`. It had the original simple implementation of routing and was published to pub as `route`. Then `experimental_hierarchical` branch came into existence with the fancy hierarchical router, which was later adopted by angular.dart for which purpose it was "forked" on pub as `route_hierarchical`. Somewhere in between, `0.5.0` branch came into existence with an effort to make hierarchical router cleaner, easier, better. Unfortunately, it wasn't progressing very fast due to lack of time. Meanwhile, as angular.dart was adding more users maintaining `route_hierarchical` in a branch was getting harder and harder and decision was made to fork it to https://github.com/angular/route.dart.

As it stands right now:
- `master` branch in `dart-lang/route` is the legacy (if I may, obsolete) code
- `experimental_hierarchical` branch is frozen and moved to `angular/route.dart`
- `0.5.0` in `dart-lang/route` branch is possibly the future of Dart routing (we'll have to wait and see)

**Comment by vicb** [comment]
@pavelgj Thanks for your detailed explanation. 

Do you think you can update the README.md with this text in the header ?  that would be _really_ helpful. Settings the default PR target branch to 0.5.0 in github might also help.

**Comment by pavelgj** [comment]
@sethladd Seth, how do you think we should handle the message?

**Comment by sethladd** [comment]
@pavelgj we could submit a PR with your explanation in the README. @justinfagnani any thoughts?

We could also merge 0.5.0 into master, which should help.

**Pull request closed without merging**
